FROM tiangolo/uwsgi-nginx:python3.8

WORKDIR /app

COPY requirements.txt /tmp/requirements.txt

RUN set -ex \
    && echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster main non-free contrib" > /etc/apt/sources.list \
    && echo "deb-src http://mirrors.tuna.tsinghua.edu.cn/debian/ buster main non-free contrib" >> /etc/apt/sources.list \
    && echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian-security/ buster/updates main" >> /etc/apt/sources.list \
    && echo "deb-src http://mirrors.tuna.tsinghua.edu.cn/debian-security/ buster/updates main" >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get install --no-install-recommends -y libpq-dev libjpeg-dev zlib1g-dev libfreetype6-dev wait-for-it \
    && pip install -r /tmp/requirements.txt \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY nginx.conf /etc/nginx/conf.d/

COPY . /app
EXPOSE 80

CMD ["bash", "/app/docker-entrypoint_aio.sh"]
